apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feed-reader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
      - name: feed-reader
        image: gcr.io/my-first-cluster-150608/feed-reader:v1
        env:
        - name: RACK_ENV
          value: production
        ports:
        - containerPort: 4567

